Fix warning of miri
Previously int GlobalLogger.init() will transmute &mut self to a
static reference for log::set_logger()

error: Undefined Behavior: trying to retag from <355141> for SharedReadOnly permission at alloc137696[0x20],
 but that tag does not exist in the borrow stack for this location
     |
1519 |         unsafe { LOGGER }
     |                  ^^^^^^
     |                  |
     |                  trying to retag from <355141> for SharedReadOnly permission at alloc137696[0x20],
 but that tag does not exist in the borrow stack for this location
     |                  this error occurs as part of retag at alloc137696[0x8..0x30]
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <355141> was created by a SharedReadOnly retag at offsets [0x20..0x48]
     |
14   |     let _ = recipe::env_logger("LOG_FILE", "LOG_LEVEL").build().expect("log setup");